name: todo_app
description: "Lista de tarefas"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter  
  
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  lottie: ^3.1.3
  form_validator: ^2.1.1
  flutter_native_splash: ^2.4.0  
  loading_indicator: ^3.1.1
  vibration: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
        
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:      
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700

flutter_icons: 
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app_icon.png"
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  
flutter_native_splash:
  color: "#00897B"
  image: "assets/images/app_icon_secondary.png"
  android_12:
    image: "assets/images/app_icon_secondary.png"
    icon_background_color: "#00897B"
  android: true
  ios: true
  web: false